---
label: Products
hide_body: false
fields:
- name: name
  type: text
  config:
    required: false
  label: Name
  description: The name of the product.
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Description
  description: The description of the product
- name: price
  type: number
  label: Price
  description: The price of the product.
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
- name: image
  type: file
  config:
    maxSize: 64
  label: Image
  description: The image for the product.
pages:
- src/products/raspberry-pi-model-4-b-quad-core-wifi-bluetooth.md
